#!/bin/sh

mkdir -p package/{deb-systemv,deb-upstart,rpm-systemd}

DISTRO=Ubuntu fpm -p package/deb-upstart -f -t deb -s python --python-install-lib /usr/lib/python2.7/dist-packages --python-bin=$(which python2.7) --no-python-fix-name setup.py
DISTRO=centos fpm -p package/rpm-systemd -f -t rpm -s python --python-install-lib /usr/lib/python2.7/site-packages --python-bin=$(which python2.7) --no-python-fix-name setup.py
DISTRO=debian fpm -p package/deb-systemv -f -t deb -s python --python-install-lib /usr/lib/python2.7/dist-packages --python-bin=$(which python2.7) --no-python-fix-name setup.py
