#!/bin/bash

echo "Cleaning package directory"
rm -rf package/* &> /dev/null
echo "Creating package directories"
mkdir -vp package/{deb-systemv,deb-upstart,rpm-systemd,deb-systemd}

install_scripts=" --before-install scripts/pre-install --after-install scripts/post-install "
python_args() {
  echo " -s python --python-install-lib /usr/lib/python2.7/$1 --python-bin=$(which python2.7) --no-python-fix-name --python-install-bin /usr/bin"
}

DISTRO=Ubuntu fpm -p package/deb-upstart -f -t deb $(python_args dist-packages) $install_scripts setup.py
DISTRO=centos fpm -p package/rpm-systemd -f -t rpm $(python_args site-packages) $install_scripts setup.py
RELEASE=7 DISTRO=debian fpm -p package/deb-systemv -f -t deb $(python_args dist-packages) $install_scripts setup.py
RELEASE=8 DISTRO=debian fpm -p package/deb-systemd -f -t deb $(python_args dist-packages) $install_scripts setup.py
